### ISSUE TITLE
Can't Get Local Dev Environment Working - Error: spawn /wasmedge ENOENT

### ISSUE THREAD

**Issue by Pandaphobic** [second-state/vercel-wasm-runtime#3]
### What's happening
I can't seem to get this working in a local WSL dev environment. It deploys to Vercel / Netlify and processes the image as expected. On the loca side, the server crashes as soon as you click "run wasm"

### These are the steps I've taken:

1. wasmedge runtime installed per [WASM Edge Book](https://wasmedge.org/book/en/start/install.html)

2. Ran the ./pre.sh file with success / no errors

3. ```yarn dev``` Brings up the front end no problem

### Troubleshooting
- updated WSL
- updated / upgraded distro (Ubuntu 20.04.3 LTS)
- completely removed and reinstall wasmedge
- deleted and cloned repo

### This is when it happens:

Uploading image works just fine. Once you click "Run WASM" nextjs / node crashes with the error below. On the FE it just shows the little broken image.
![Screenshot_1](https://user-images.githubusercontent.com/11794877/152447676-2b149c70-06c1-43ab-bb97-fc8091b4b228.png)

Environment:
- Node v16.3.0
- Ubuntu 20.04.3 LTS
- Chrome 97.0.4692.99 (Windows x64)

```wait  - compiling...
event - compiled successfully
API resolved without sending a response for /api/hello, this may result in stalled requests.
Error: spawn /wasmedge ENOENT

    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /wasmedge',
  path: '/wasmedge',
  spawnargs: [ '/grayscale.wasm' ]
}
node:_http_outgoing:574
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:363:5)
    at ServerResponse.setHeader (node:_http_outgoing:574:11)
    at ChildProcess.<anonymous> (/home/chris/Coding/vercel-wasm-runtime/.next/server/pages/api/hello.js:119:9)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Socket.<anonymous> (node:internal/child_process:453:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:661:12) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by DarumaDocker** [comment]
@Pandaphobic Sorry for the late reply. You can find the `spawning` command is `/wasmedge` and can't find it. The code in `api/hello.js` uses the `__dirname` to locate the current work directory, but get `/`.
It's a known issue of next.js https://github.com/vercel/next.js/issues/10943.
As suggested you can change `__dirname` to `process.cwd()`.
But there is another issue when you launch this project on your local machine, that is to say the `bodyParser`.
You should disable the default `bodyParser` of `next.js` and read the body of request by yourself.
The working `api/hello.js` shows below:
```javascript
const fs = require('fs');
const { spawn } = require('child_process');
const path = require('path');

export const config = {
  api: {
    bodyParser: false
  }
};

export default (req, res) => {
  const wasmedge = spawn(path.join(process.cwd(), 'api/wasmedge'), [path.join(process.cwd(), 'api/grayscale.so')]);

  let d = [];
  wasmedge.stdout.on('data', (data) => {
    d.push(data);
  });

  wasmedge.on('close', (code) => {
    let buf = Buffer.concat(d);

    res.setHeader('Content-Type', req.headers['image-type']);
    res.send(buf);
  });

  let body = [];
  req.on('data', (chunk) => {
    body.push(chunk);
  }).on('end', () => {
    body = Buffer.concat(body);
    // at this point, `body` has the entire request body stored in it as a string
    wasmedge.stdin.write(body);
    wasmedge.stdin.end('');
  });
}
```

**Comment by YuriGor** [comment]
In my case I had same issue because locall pre.sh was not called by vercel cli in dev mode.
I executed it manually, .so file was built and everything started working
